services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    depends_on:
      - client
    restart: always
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api
    container_name: react-frontend
    ports:
      - "4173:4173"
    stdin_open: true
    tty: true
    restart: always

  db:
    image: postgres:latest
    container_name: db-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: CodingIsASuperpower!
      POSTGRES_DB: postgres
      pgdata: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  
  loki:
    image: grafana/loki:latest

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./configs/promtail-config.yaml:/etc/promtail/config.yaml
      - ./api:/var/log/api:ro  # Make sure FastAPI logs here
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    restart: always


  grafana:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

    image: grafana/grafana:latest
    ports:
      - "8899:3000"
    volumes:
      - ./configs/grafana-datasource.yml:/etc/grafana/provisioning/datasources/ds.yaml

    depends_on:
      - loki
    restart: always

volumes:
  pgdata: