services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    depends_on:
      - client
    restart: always
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:4173"
    stdin_open: true
    tty: true
    restart: always

  db:
    image: postgres:latest
    container_name: db-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: $POSTGRES_DB
      pgdata: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
volumes:
  pgdata: