apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lunchbox
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: jesus6190/lunchbox_api:7
        ports:
        - containerPort: 8000
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_CONN
