apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lunchbox
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: sarahstrawberries/lunchbox_api:7
        ports:
        - containerPort: 8000
        readinessProbe:
          httpsGet:
            path: /api
            port: 8000
          # exec:
          #   command:
          #   - cat
          #   - /tmp/healthy
          initialDelaySeconds: 15
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpsGet:
            path: /api
            port: 8000
          # exec:
          #   command:
          #   - cat
          #   - /tmp/healthy
          initialDelaySeconds: 5
          failureThreshold: 10
          periodSeconds: 5
        env:
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_CONN
