apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: lunchbox
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: jesus6190/lunchbox_client:59
        ports:
        - containerPort: 4173
        readinessProbe:
          httpGet:
            path: /
            port: 4173
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 4173
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: DB_CONN
          # valueFrom:
            # secretKeyRef:
              # name: db-secret
              # key: DB_CONN
