apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
  namespace: lunchbox
data:
  otel-config.yaml: |
    receivers:
      filelog:
        include:
          - /var/log/app/*.log
        start_at: beginning
        operators:
          - type: json_parser
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%d %H:%M:%S,%f'
            severity:
              parse_from: attributes.level
            attributes:
              log_type: fastapi

    exporters:
      loki:
        endpoint: "http://lunchbox6.duckdns.org:3100/loki/api/v1/push"

    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [loki]