apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
  namespace: lunchbox
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    # exporters:
    #   prometheus:
    #     endpoint: "0.0.0.0:8889"
    #   otlphttp:  # Use OTLP to send logs instead
    #     endpoint: "http://loki:3100/otlp"

    service:
      pipelines:
        # metrics:
        #   receivers: [otlp]
        #   exporters: [prometheus]
        logs:
          receivers: [otlp]
          exporters: [otlphttp]