apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
  namespace: lunchbox
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"

      prometheus:
        endpoint: "0.0.0.0:8889"

      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus, debug]

        logs:
          receivers: [otlp]
          exporters: [loki, debug]

        traces:
          receivers: [otlp]
          exporters: [zipkin, debug]