apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
  namespace: lunchbox
data:
  otel-config.yaml: |
    receivers:
      filelog:
        include:
          - /var/log/app/*.log
        start_at: beginning

    exporters:
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

    service:
      pipelines:
        logs:
          receivers: [filelog]
          exporters: [loki]