apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-configmap
  namespace: lunchbox
data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch: {}

    exporters:
      loki:
        endpoint: "http://loki:3100/loki/api/v1/push"

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
