apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lunchbox
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "otel"
        static_configs:
          - targets: ["otel-collector-service:8889"]

      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [http_2xx]  # Look for a HTTP 200 response.
        static_configs:
          - targets:
            - http://lunchbox6.duckdns.org/api/health 
            - http://lunchbox6.duckdns.org

        relabel_configs:  
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
            
      - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
        static_configs:
          - targets: ['127.0.0.1:9115']
