apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lunchbox
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "otel"
        static_configs:
          - targets: ["otel-collector-service:8889"]
