apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: pr-${PR_NUMBER}
type: Opaque
stringData:
  DB_NAME: postgres
  DB_USER: app_admin
  DB_PASSWORD: "CodingIsASuperpower!!"
  DB_CONN: "Host=db-svc;Database=postgres;Username=app_admin;Password=CodingIsASuperpower!!"
