receivers:

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
  debug:
    verbosity: detailed

  # prometheus:
  #   endpoint: 0.0.0.0:8889
  #   namespace: default

  # zipkin:
  #   endpoint: http://zipkin:9411/api/v2/spans

# service:
#   pipelines:
  
#     traces:
#       receivers: [otlp]
#       exporters: [zipkin, debug]

#     metrics:
#       receivers: [otlp]
#       processors: []
#       exporters: [prometheus, debug]
