global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "fastapi-backend"
    metrics_path: /health
    scrape_interval: 15s
    static_configs:
      - targets: ["fastapi-backend-service:8000"]