name: Restore From Dump

on:
  push:
  workflow_dispatch:

jobs:
  restore_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get db pod
        id: find_db
        run: |
          DB_POD=$(kubectl get pods -n lunchbox \
            --sort-by=.metadata.creationTimestamp \
            --no-headers | grep 'db-deployment' | grep 'Running' | tail -n1 | awk '{print $1}')
          echo "db_pod=$DB_POD" >> $GITHUB_OUTPUT

      - name: Get latest backup pod
        id: find_backup
        run: |
          BACKUP_POD=$(kubectl get pods -n lunchbox \
            --sort-by=.metadata.creationTimestamp \
            --no-headers | grep 'db-backup' | tail -n1 | awk '{print $1}')
          echo "backup_pod=$BACKUP_POD" >> "$GITHUB_OUTPUT"

      - name: Copy dump from backup pod
        run: |
          kubectl cp lunchbox/${{ steps.find_backup.outputs.backup_pod }}:/backups/db_backup.sql ./dump.sql

      - name: Restore database
        run: |
          kubectl cp ./dump.sql lunchbox/${{ steps.find_db.outputs.db_pod }}:/tmp/dump.sql
          kubectl exec -n lunchbox ${{ steps.find_db.outputs.db_pod }} -- \
          pg_restore -U app_admin -d postgres /tmp/dump.sql
 