name: Deploy FastAPI to Staging (DuckDNS)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Install Black
        run: pip install black

      - name: Lint with Black
        run: black --check .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd api
            docker build -t jesus6190/lunchbox_api:${{github.run_number}} .
            docker push jesus6190/lunchbox_api:${{github.run_number}}


  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "🚨 @everyone Build failed on **${{ github.repository }}** in branch `${{ github.ref_name }}`!\nCheck the run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
               }' \
               "$DISCORD_WEBHOOK"

  deploy_to_kubernetes:
    runs-on: self-hosted
    # setup_for_deployment: notify
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kube/api-deployment.yml
          kubectl apply -f ./kube/api-svc.yml