name: Deploy Frontend to Staging (DuckDNS)

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy_web_staging:
    runs-on: self-hosted
    steps:
        - name: Checkout code
          uses: actions/checkout@v4  
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Build and Push Docker Image
          run: |
            docker build \
              -t jesus6190/lunchbox_client:${{github.run_number}} \
              --build-arg VITE_API_URL=https://lunchbox6.duckdns.org/api \
              ./client
            docker push jesus6190/lunchbox_client:${{github.run_number}}
  
        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f ./kube/app-deployment.yml
            kubectl apply -f ./kube/app-svc.yml        
            kubectl apply -f ./kube/app-ingress.yml 