name: Deploy FastAPI to Staging (DuckDNS)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy_api_staging:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd api
          docker build -t jesus6190/lunchbox_api:${{github.run_number}} .
          docker push jesus6190/lunchbox_api:${{github.run_number}}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kube/api-deployment.yml
          kubectl apply -f ./kube/api-svc.yml